n1 = input("enter name:")
n2 = input("enter name:")
n3 = input("enter name:")
n4 = input("enter name:")
n5 = input("enter name:")
n6 = input("enter name:")
n7 = input("enter name:")
n8 = input("enter name:")
n9 = input("enter name:")
n10= input("enter name:")
admin = input("enter youre admin:")
n1 = n1.title()
n2 = n2.title()
n3 = n3.title()
n4 = n4.title()
n5 = n5.title()
n6 = n6.title()
n8 = n7.title()
n8 = n8.title()
n9 = n9.title()
n10 = n10.title()
print(n1,n2,n3,n4,n5,n6,n7,n8,n9,n10)

f = n1.count(admin) + n2.count(admin) + n3.count(admin) + n4.count(admin) + n5.count(admin) + n6.count(admin) + n7.count(admin) + n8.count(admin) + n9.count(admin) + n10.count(admin)
n_admin = admin.title()
s = n1.count(n_admin) + n2.count(n_admin) + n3.count(n_admin) + n4.count(n_admin) + n5.count(n_admin) + n6.count(n_admin) + n7.count(n_admin) + n8.count(n_admin) + n9.count(n_admin) + n10.count(n_admin)
f += s
print(f)
